language: node_js
node_js:
  - "6"

install:
  - cd backend && npm install && cd ..
  - cd cesium_frontend && npm install && cd ..

script: backend/travis_ci_runner.sh
script: cesium_frontend/travis_ci_runner.sh
